export const products = 
    [
        {
            id: 1,
            imgAlt: 'Chuck 70 De Luxe Heel Chrome Queen Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a08103c_a_107x1_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck 70 De Luxe Heel Chrome Queen Preto',
            type: 'FEMININO CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: '799,90',
            variations: '1 cor',
            productUrl: 'chuck-70-de-luxe-heel-chrome-queen-preto',
            productSize: '0'
        },
        {
            id: 2,
            imgAlt: 'Vans the Lizzie Cloud',
            imgLink: 'https://cdn.shopify.com/s/files/1/0581/5900/5854/files/VANSLIZZIEFATIGUEBLACK_600x600.png?v=1691166617',
            name: 'Vans the Lizzie Cloud',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'OFF THE WALL',
            price: '649,90',
            variations: '1 cor',
            productUrl: 'vans-the-lizzie-cloud',
            productSize: '0'
        },
        {
            id: 3,
            imgAlt: 'Nike Court Vision Mid Nn All Black',
            imgLink: 'https://images.tcdn.com.br/img/img_prod/1127564/180_tenis_nike_court_vision_mid_nn_all_black_1662_1_84b4860aa5c23c947606bf6707853c6f.jpg',
            name: 'Nike Court Vision Mid Nn All Black',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'JUST DO IT',
            price: '649,90',
            variations: '1 cor',
            productUrl: 'nike-court-vision-mid-nn-all-black',
            productSize: '0'
        },
        {
            id: 4,
            imgAlt: 'Converse X Martine Ali Chuck 70 Xhi Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a08651c_a_107x1_1_2.png?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:&format=jpeg',
            name: 'Converse X Martine Ali Chuck 70 Xhi Preto',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: '1.099,90',
            variations: '1 cor',
            productUrl: 'converse-x-martine-ali-chuck-70-xhi-preto',
            productSize: '0'
        },
        {
            id: 5,
            imgAlt: 'Chuck Taylor All Star Modern Lift Chrome Queen Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a08102c_a_107x1_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck Taylor All Star Modern Lift Chrome Queen Preto',
            type: 'FEMININO CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: '599,90',
            variations: '1 cor',
            productUrl: 'chuck-taylor-all-star-modern-lift-chrome-queen-preto',
            productSize: '0'
        },
        {
            id: 6,
            imgAlt: 'Tênis Converse Chuck Taylor All Star Hi Future Utility',
            imgLink: 'https://espacotenis.vteximg.com.br/arquivos/ids/171907-1000-1000/converse-hi-future-utility-branco.jpg?v=638191505258630000',
            name: 'Converse Chuck Taylor All Star Hi Future Utility',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: '449,90',
            variations: '1 cor',
            productUrl: 'tenis-coverse-chuck-taylor-all-star-hi-future-utility',
            productSize: '0'
        },
        {
            id: 7,
            imgAlt: 'Vans Classic',
            imgLink: 'https://www.tradeinn.com/f/125/1252969/vans-sapatos-sem-cadarco-classic.jpg',
            name: 'Vans  Classic',
            type: 'UNISEX CANO BAIXO',
            catchPhrase: 'OFF THE WALL',
            price: '249,90',
            variations: '1 cor',
            productUrl: 'vans-sem-cadarço-classic',
            productSize: '0'
        },
        {
            id: 8,
            imgAlt: 'Tênis Nike Air Max 97',
            imgLink: 'https://images.tcdn.com.br/img/img_prod/1048024/tenis_nike_air_max_97_branco_921826_101_6729_1_1ed3ff085def62045397ec3725058f42.jpg',
            name: 'Tênis Nike Air Max 97',
            type: 'UNISEX CANO BAIXO',
            catchPhrase: 'JUST DO IT',
            price: '1049,90',
            variations: '1 cor',
            productUrl: 'tenis-nike-air-max-97',
            productSize: '0'
        },
        {
            id: 9,
            imgAlt: 'Chuck Taylor All Star Chrome Queen Branco',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a06444c_a_107x1_6.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck Taylor All Star Chrome Queen Branco',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: '549,90',
            variations: '1 cor',
            productUrl: 'chuck-taylor-all-star-chrome-queen-branco',
            productSize: '0'
        },
        {
            id: 10,
            imgAlt: 'Vans Benegas X Enarson White',
            imgLink: 'https://www.tillys.com/on/demandware.static/-/Sites-master-catalog/default/dw51976e42/tillys/images/catalog/1000x1000/267631150a.jpg',
            name: 'Vans Benegas X Enarson White',
            type: 'UNISEX CANO BAIXO',
            catchPhrase: 'OFF THE WALL',
            price: '599,90',
            variations: '1 cor',
            productUrl: 'tenis-bmx-sk8-hi-benegas-x-enarson-white',
            productSize: '0'
        },
    ]