export const products = 
    [
        {
            id: 'id',
            imgAlt: 'Chuck 70 De Luxe Heel Chrome Queen Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a08103c_a_107x1_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck 70 De Luxe Heel Chrome Queen Preto',
            type: 'FEMININO CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: 799.90,
            variations: '1 cor',
            productUrl: 'chuck-70-de-luxe-heel-chrome-queen-preto',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Vans the Lizzie Cloud',
            imgLink: 'https://cdn.shopify.com/s/files/1/0581/5900/5854/files/VANSLIZZIEFATIGUEBLACK_600x600.png?v=1691166617',
            name: 'Vans the Lizzie Cloud',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'OFF THE WALL',
            price: 649.90,
            variations: '1 cor',
            productUrl: 'vans-the-lizzie-cloud',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Nike Court Vision Mid Nn All Black',
            imgLink: 'https://images.tcdn.com.br/img/img_prod/1127564/180_tenis_nike_court_vision_mid_nn_all_black_1662_1_84b4860aa5c23c947606bf6707853c6f.jpg',
            name: 'Nike Court Vision Mid Nn All Black',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'JUST DO IT',
            price: 649.90,
            variations: '1 cor',
            productUrl: 'nike-court-vision-mid-nn-all-black',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Converse X Martine Ali Chuck 70 Xhi Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a08651c_a_107x1_1_2.png?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:&format=jpeg',
            name: 'Converse X Martine Ali Chuck 70 Xhi Preto',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: 1090.00,
            variations: '1 cor',
            productUrl: 'converse-x-martine-ali-chuck-70-xhi-preto',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Chuck Taylor All Star Modern Lift Chrome Queen Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a08102c_a_107x1_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck Taylor All Star Modern Lift Chrome Queen Preto',
            type: 'FEMININO CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: 599.90,
            variations: '1 cor',
            productUrl: 'chuck-taylor-all-star-modern-lift-chrome-queen-preto',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Tênis Converse Chuck Taylor All Star Hi Future Utility',
            imgLink: 'https://espacotenis.vteximg.com.br/arquivos/ids/171907-1000-1000/converse-hi-future-utility-branco.jpg?v=638191505258630000',
            name: 'Converse Chuck Taylor All Star Hi Future Utility',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: 449.90,
            variations: '1 cor',
            productUrl: 'tenis-coverse-chuck-taylor-all-star-hi-future-utility',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Vans Classic',
            imgLink: 'https://www.tradeinn.com/f/125/1252969/vans-sapatos-sem-cadarco-classic.jpg',
            name: 'Vans  Classic',
            type: 'UNISEX CANO BAIXO',
            catchPhrase: 'OFF THE WALL',
            price: 249.90,
            variations: '1 cor',
            productUrl: 'vans-sem-cadarço-classic',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Tênis Nike Air Max 97',
            imgLink: 'https://images.tcdn.com.br/img/img_prod/1048024/tenis_nike_air_max_97_branco_921826_101_6729_1_1ed3ff085def62045397ec3725058f42.jpg',
            name: 'Tênis Nike Air Max 97',
            type: 'UNISEX CANO BAIXO',
            catchPhrase: 'JUST DO IT',
            price: 1049.90,
            variations: '1 cor',
            productUrl: 'tenis-nike-air-max-97',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Chuck Taylor All Star Chrome Queen Branco',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a06444c_a_107x1_6.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck Taylor All Star Chrome Queen Branco',
            type: 'UNISEX CANO ALTO',
            catchPhrase: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: 549.90,
            variations: '1 cor',
            productUrl: 'chuck-taylor-all-star-chrome-queen-branco',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Vans Benegas X Enarson White',
            imgLink: 'https://www.tillys.com/on/demandware.static/-/Sites-master-catalog/default/dw51976e42/tillys/images/catalog/1000x1000/267631150a.jpg',
            name: 'Vans Benegas X Enarson White',
            type: 'UNISEX CANO BAIXO',
            catchPhrase: 'OFF THE WALL',
            price: 599.90,
            variations: '1 cor',
            productUrl: 'vans-hi-benegas-x-enarson-white',
            productSize: '0'
        },
        {
            id: 'id',
            imgAlt: 'Slacker-160',
            imgLink: 'https://demoniacult.com/cdn/shop/products/slacker-160-w_640x640_crop_center.jpg?v=1628719610',
            name: 'Slacker-160',
            type: 'FEMININO CANO ALTO',
            catchPhrase: 'Definindo moda alternativa',
            price: 615.00,
            variations: '1 cor',
            productUrl: 'slacker-160w',
            productSize: '0',
        },
        {
            id: 'id',
            imgAlt: 'Camel-311',
            imgLink: 'https://demoniacult.com/cdn/shop/products/camel-311-wpu_85460dbe-f010-41d7-8b82-71b586fadd36_640x640_crop_center.jpg?v=1633036501',
            name: 'Camel-11',
            type: 'FEMININO CANO ALTO',
            catchPhrase: 'Definindo moda alternativa',
            price: 690.00,
            variations: '1 cor',
            productUrl: 'camel-311wpu',
            productSize: '0',
        },
        {
            id: 'id',
            imgAlt: 'Gravedigger-250',
            imgLink: 'https://demoniacult.com/cdn/shop/products/gravedigger-250-bvl_640x640_crop_center.jpg?v=1582160150',
            name: 'Gravedigger-250',
            type: 'FEMININO CANO ALTO',
            catchPhrase: 'Definindo moda alternativa',
            price: 805.00,
            variations: '1 COR',
            productUrl: 'gravedigger-250bvl',
            productSize: '0',
        },
        {
            id: 'id',
            imgAlt: 'Shaker-70',
            imgLink: 'https://demoniacult.com/cdn/shop/products/shaker-70-bvl_640x640_crop_center.jpg?v=1612829860',
            name: 'Shaker-70',
            type: 'FEMININO CANO ALTO',
            catchPhrase: 'Definindo moda alternativa',
            price: 680.00,
            variations: '1 cor',
            productUrl: 'shaker-70',
            productSize: '0',
        },
        {
            id: 'id',
            imgAlt: 'Shaker-52',
            imgLink: 'https://demoniacult.com/cdn/shop/products/shaker-52-wvl_640x640_crop_center.jpg?v=1633036981',
            name: 'Shaker-52',
            type: 'FEMININO CANO ALTO',
            catchPhrase: 'Definindo moda alternativa',
            price: 535.00,
            variations: '1 cor',
            productUrl: 'shaker-52',
            productSize: '0',
        },
        {
            id: 'id',
            imgAlt: 'Chuck Taylor All Star City Trek Marrom',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a06601c_a_107x1_3.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck Taylor All Star City Trek Marrom',
            type: 'MASCULINO CANO ALTO',
            catchPhrase: 'Defina o seu padrão audacioso com esse icônico All Stat City Trek.',
            price: 499.90,
            variations: '1 cor',
            productUrl: 'chuck-taylor-all-star-city-trek-cano-alto-normal-marrom',
            productSize: '0',
        },
    ]